# This rule is not used by the project spectrum-x-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the spectrumx.nvidia.com.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: spectrum-x-operator
    app.kubernetes.io/managed-by: kustomize
  name: spectrumxrailpoolconfig-editor-role
rules:
- apiGroups:
  - spectrumx.nvidia.com
  resources:
  - spectrumxrailpoolconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - spectrumx.nvidia.com
  resources:
  - spectrumxrailpoolconfigs/status
  verbs:
  - get
