# This rule is not used by the project spectrum-x-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over spectrumx.nvidia.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: spectrum-x-operator
    app.kubernetes.io/managed-by: kustomize
  name: spectrumxrailpoolconfig-admin-role
rules:
- apiGroups:
  - spectrumx.nvidia.com
  resources:
  - spectrumxrailpoolconfigs
  verbs:
  - '*'
- apiGroups:
  - spectrumx.nvidia.com
  resources:
  - spectrumxrailpoolconfigs/status
  verbs:
  - get
