apiVersion: spectrumx.nvidia.com/v1alpha1
kind: SpectrumXRailPoolConfig
metadata:
  labels:
    app.kubernetes.io/name: spectrum-x-operator
    app.kubernetes.io/managed-by: kustomize
  name: spectrumxrailpoolconfig-sample
spec:
  # TODO(user): Add fields here
